sonar.projectKey=taskflow
sonar.projectName=TaskFlow
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/coverage/**,.next/**,dist/**,docker/**,terraform/**,helm/**,kubernetes/**,grafana/**
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.coverage.exclusions=src/**/*.d.ts,src/app/**/layout.tsx,src/app/**/page.tsx
sonar.cpd.exclusions=src/components/ui/**
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6478
sonar.issue.ignore.multicriteria.e1.resourceKey=src/**/*.tsx
