apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskflow.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
data:
  FRONTEND_PORT: {{ .Values.service.frontend.port | quote }}
  BACKEND_PORT: {{ .Values.service.backend.port | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
