{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | quote }}
  NEXTAUTH_URL: {{ .Values.secrets.NEXTAUTH_URL | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
{{- end }}
