apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app.kubernetes.io/name: {{ include "taskflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app.kubernetes.io/name: {{ include "taskflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: http
